## Load data

In [1]:
import pandas as pd

medal = pd.read_csv("../data/raw/medals_country.csv")
medal.head()

   Rank                   Country  Gold  Silver  Bronze  Total
0     1                    Norway    18      12      11     41
1     2  United States of America    12      12       9     33
2     3               Netherlands    10       7       3     20
3     4                     Italy    10       6      14     30
4     5                   Germany     8      10       8     26

In [2]:
population_wiki = pd.read_csv("../data/raw/population_wikipedia.csv")
population_wiki.head()

         country  population
0          India  1417492000
1          China  1404890000
2  United States   341784857
3      Indonesia   288315089
4       Pakistan   241499431

In [3]:
population_world = pd.read_csv("../data/raw/worldometers_population.csv")
population_world.head()

         country  population
0          India  1476625576
1          China  1412914089
2  United States   349035494
3      Indonesia   287886782
4       Pakistan   259299791

In [4]:
temp = pd.read_csv("../data/raw/temperature.csv")
temp.head()

       country  year  temperature
0  Afghanistan  1990        9.466
1  Afghanistan  1991        8.369
2  Afghanistan  1992        8.203
3  Afghanistan  1993        8.754
4  Afghanistan  1994        8.812

In [5]:
gdp = pd.read_csv("../data/raw/gdp_per_capita.csv")
gdp.head()

          country country_code  region  gdp_per_capita_usd
0     Afghanistan          AFG     NaN          413.757895
1         Albania          ALB     NaN         9730.869219
2         Algeria          DZA     NaN         5370.477235
3  American Samoa          ASM     NaN                 NaN
4         Andorra          AND     NaN        46812.426101

## Merge Medal and Population data

In [6]:
df = pd.merge(medal, population_wiki, left_on='Country', right_on='country', how='left')
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population
0,1,Norway,18,12,11,41,Norway,5627400.0
1,2,United States of America,12,12,9,33,NaN,NaN
2,3,Netherlands,10,7,3,20,Netherlands,18131264.0
3,4,Italy,10,6,14,30,Italy,58956726.0
4,5,Germany,8,10,8,26,Germany,83497147.0
5,6,France,8,9,6,23,France,69081996.0
6,7,Sweden,8,6,4,18,Sweden,10604464.0
7,8,Switzerland,6,9,8,23,Switzerland,9104063.0
8,9,Austria,5,8,5,18,Austria,9219113.0
9,10,Japan,5,7,12,24,Japan,122850000.0
10,11,Canada,5,7,9,21,Canada,41472081.0
11,12,People's Republic of China,5,4,6,15,NaN,NaN
12,13,Republic of Korea,3,4,3,10,NaN,NaN
13,14,Australia,3,2,1,6,Australia,27724744.0
14,15,Great Britain,3,1,1,5,NaN,NaN
15,16,Czechia,2,2,1,5,Czechia,10897178.0
16,17,Slovenia,2,1,1,4,Slovenia,2133852.0
17,18,Spain,1,0,2,3,Spain,49570725.0
18,19,Brazil,1,0,0,1,Brazil,213421037.0
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20518005.0
20,21,Poland,0,3,1,4,Poland,37332000.0
21,22,New Zealand,0,2,1,3,New Zealand,5342000.0
22,23,Finland,0,1,5,6,Finland,5657608.0
23,24,Latvia,0,1,1,2,Latvia,1823500.0
24,25,Denmark,0,1,0,1,Denmark,6028459.0
25,25,Estonia,0,1,0,1,Estonia,1362954.0
26,25,Georgia,0,1,0,1,Georgia,3704500.0
27,28,Bulgaria,0,0,2,2,Bulgaria,6437360.0
28,29,Belgium,0,0,1,1,Belgium,11928465.0

In [7]:
df.loc[df['population'].isna(), 'Country']

1       United States of America
11    People's Republic of China
12             Republic of Korea
14                 Great Britain
Name: Country, dtype: str

In [8]:
country_mapping = {
    'United States of America': 'United States',
    "People's Republic of China": 'China',
    'Republic of Korea': 'South Korea',
    'Great Britain': 'United Kingdom'
}

df['country'] = df['Country'].replace(country_mapping)

In [9]:
df = df.drop(columns=['population'])
df = df.merge(population_wiki, on='country', how='left')

In [10]:
df = df.rename(columns={'population': 'population_wiki'})

In [11]:
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population_wiki
0,1,Norway,18,12,11,41,Norway,5627400
1,2,United States of America,12,12,9,33,United States,341784857
2,3,Netherlands,10,7,3,20,Netherlands,18131264
3,4,Italy,10,6,14,30,Italy,58956726
4,5,Germany,8,10,8,26,Germany,83497147
5,6,France,8,9,6,23,France,69081996
6,7,Sweden,8,6,4,18,Sweden,10604464
7,8,Switzerland,6,9,8,23,Switzerland,9104063
8,9,Austria,5,8,5,18,Austria,9219113
9,10,Japan,5,7,12,24,Japan,122850000
10,11,Canada,5,7,9,21,Canada,41472081
11,12,People's Republic of China,5,4,6,15,China,1404890000
12,13,Republic of Korea,3,4,3,10,South Korea,51111158
13,14,Australia,3,2,1,6,Australia,27724744
14,15,Great Britain,3,1,1,5,United Kingdom,69487000
15,16,Czechia,2,2,1,5,Czechia,10897178
16,17,Slovenia,2,1,1,4,Slovenia,2133852
17,18,Spain,1,0,2,3,Spain,49570725
18,19,Brazil,1,0,0,1,Brazil,213421037
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20518005
20,21,Poland,0,3,1,4,Poland,37332000
21,22,New Zealand,0,2,1,3,New Zealand,5342000
22,23,Finland,0,1,5,6,Finland,5657608
23,24,Latvia,0,1,1,2,Latvia,1823500
24,25,Denmark,0,1,0,1,Denmark,6028459
25,25,Estonia,0,1,0,1,Estonia,1362954
26,25,Georgia,0,1,0,1,Georgia,3704500
27,28,Bulgaria,0,0,2,2,Bulgaria,6437360
28,29,Belgium,0,0,1,1,Belgium,11928465

In [12]:
df = df.merge(population_world, on='country', how='left')
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population_wiki,population
0,1,Norway,18,12,11,41,Norway,5627400,5.652989e+06
1,2,United States of America,12,12,9,33,United States,341784857,3.490355e+08
2,3,Netherlands,10,7,3,20,Netherlands,18131264,1.844878e+07
3,4,Italy,10,6,14,30,Italy,58956726,5.892617e+07
4,5,Germany,8,10,8,26,Germany,83497147,8.364426e+07
5,6,France,8,9,6,23,France,69081996,6.674640e+07
6,7,Sweden,8,6,4,18,Sweden,10604464,1.070105e+07
7,8,Switzerland,6,9,8,23,Switzerland,9104063,9.007798e+06
8,9,Austria,5,8,5,18,Austria,9219113,9.107266e+06
9,10,Japan,5,7,12,24,Japan,122850000,1.224277e+08
10,11,Canada,5,7,9,21,Canada,41472081,4.046773e+07
11,12,People's Republic of China,5,4,6,15,China,1404890000,1.412914e+09
12,13,Republic of Korea,3,4,3,10,South Korea,51111158,5.160039e+07
13,14,Australia,3,2,1,6,Australia,27724744,2.722710e+07
14,15,Great Britain,3,1,1,5,United Kingdom,69487000,6.993153e+07
15,16,Czechia,2,2,1,5,Czechia,10897178,NaN
16,17,Slovenia,2,1,1,4,Slovenia,2133852,2.114573e+06
17,18,Spain,1,0,2,3,Spain,49570725,4.785079e+07
18,19,Brazil,1,0,0,1,Brazil,213421037,2.135627e+08
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20518005,2.108363e+07
20,21,Poland,0,3,1,4,Poland,37332000,3.784319e+07
21,22,New Zealand,0,2,1,3,New Zealand,5342000,5.287479e+06
22,23,Finland,0,1,5,6,Finland,5657608,5.621739e+06
23,24,Latvia,0,1,1,2,Latvia,1823500,1.835935e+06
24,25,Denmark,0,1,0,1,Denmark,6028459,6.023520e+06
25,25,Estonia,0,1,0,1,Estonia,1362954,1.331062e+06
26,25,Georgia,0,1,0,1,Georgia,3704500,3.804642e+06
27,28,Bulgaria,0,0,2,2,Bulgaria,6437360,6.667659e+06
28,29,Belgium,0,0,1,1,Belgium,11928465,1.177464e+07

In [13]:
df[df['population'].isna()]

,Rank,Country,Gold,Silver,Bronze,Total,country,population_wiki,population
15,16,Czechia,2,2,1,5,Czechia,10897178,NaN

In [14]:
population_world[population_world['country'].str.contains("Czech")]

                     country  population
91  Czech Republic (Czechia)    10527781

In [15]:
population_world_mapping = {
    'Czech Republic (Czechia)': 'Czechia'
}

population_world['country'] = population_world['country'].replace(population_world_mapping)

In [16]:
df = df.drop(columns=['population'], errors='ignore')
df = df.merge(population_world[['country', 'population']], on='country', how='left')
df = df.rename(columns={'population': 'population_world'})

In [17]:
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population_wiki,population_world
0,1,Norway,18,12,11,41,Norway,5627400,5652989
1,2,United States of America,12,12,9,33,United States,341784857,349035494
2,3,Netherlands,10,7,3,20,Netherlands,18131264,18448775
3,4,Italy,10,6,14,30,Italy,58956726,58926166
4,5,Germany,8,10,8,26,Germany,83497147,83644258
5,6,France,8,9,6,23,France,69081996,66746401
6,7,Sweden,8,6,4,18,Sweden,10604464,10701047
7,8,Switzerland,6,9,8,23,Switzerland,9104063,9007798
8,9,Austria,5,8,5,18,Austria,9219113,9107266
9,10,Japan,5,7,12,24,Japan,122850000,122427731
10,11,Canada,5,7,9,21,Canada,41472081,40467728
11,12,People's Republic of China,5,4,6,15,China,1404890000,1412914089
12,13,Republic of Korea,3,4,3,10,South Korea,51111158,51600388
13,14,Australia,3,2,1,6,Australia,27724744,27227096
14,15,Great Britain,3,1,1,5,United Kingdom,69487000,69931528
15,16,Czechia,2,2,1,5,Czechia,10897178,10527781
16,17,Slovenia,2,1,1,4,Slovenia,2133852,2114573
17,18,Spain,1,0,2,3,Spain,49570725,47850793
18,19,Brazil,1,0,0,1,Brazil,213421037,213562666
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20518005,21083626
20,21,Poland,0,3,1,4,Poland,37332000,37843188
21,22,New Zealand,0,2,1,3,New Zealand,5342000,5287479
22,23,Finland,0,1,5,6,Finland,5657608,5621739
23,24,Latvia,0,1,1,2,Latvia,1823500,1835935
24,25,Denmark,0,1,0,1,Denmark,6028459,6023520
25,25,Estonia,0,1,0,1,Estonia,1362954,1331062
26,25,Georgia,0,1,0,1,Georgia,3704500,3804642
27,28,Bulgaria,0,0,2,2,Bulgaria,6437360,6667659
28,29,Belgium,0,0,1,1,Belgium,11928465,11774642

In [18]:
df['population'] = (df['population_wiki'] + df['population_world'])/2
df['population'] = df['population'].astype('int')
df = df.drop(columns=['population_wiki', 'population_world'])
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population
0,1,Norway,18,12,11,41,Norway,5640194
1,2,United States of America,12,12,9,33,United States,345410175
2,3,Netherlands,10,7,3,20,Netherlands,18290019
3,4,Italy,10,6,14,30,Italy,58941446
4,5,Germany,8,10,8,26,Germany,83570702
5,6,France,8,9,6,23,France,67914198
6,7,Sweden,8,6,4,18,Sweden,10652755
7,8,Switzerland,6,9,8,23,Switzerland,9055930
8,9,Austria,5,8,5,18,Austria,9163189
9,10,Japan,5,7,12,24,Japan,122638865
10,11,Canada,5,7,9,21,Canada,40969904
11,12,People's Republic of China,5,4,6,15,China,1408902044
12,13,Republic of Korea,3,4,3,10,South Korea,51355773
13,14,Australia,3,2,1,6,Australia,27475920
14,15,Great Britain,3,1,1,5,United Kingdom,69709264
15,16,Czechia,2,2,1,5,Czechia,10712479
16,17,Slovenia,2,1,1,4,Slovenia,2124212
17,18,Spain,1,0,2,3,Spain,48710759
18,19,Brazil,1,0,0,1,Brazil,213491851
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20800815
20,21,Poland,0,3,1,4,Poland,37587594
21,22,New Zealand,0,2,1,3,New Zealand,5314739
22,23,Finland,0,1,5,6,Finland,5639673
23,24,Latvia,0,1,1,2,Latvia,1829717
24,25,Denmark,0,1,0,1,Denmark,6025989
25,25,Estonia,0,1,0,1,Estonia,1347008
26,25,Georgia,0,1,0,1,Georgia,3754571
27,28,Bulgaria,0,0,2,2,Bulgaria,6552509
28,29,Belgium,0,0,1,1,Belgium,11851553

## Merge GDP data

In [19]:
df = df.merge(gdp, on='country', how='left')

In [20]:
df[df['gdp_per_capita_usd'].isna()]

,Rank,Country,Gold,Silver,Bronze,Total,country,population,country_code,region,gdp_per_capita_usd
12,13,Republic of Korea,3,4,3,10,South Korea,51355773,NaN,NaN,NaN

In [21]:
gdp[gdp['country'].str.contains('Korea', na=False)]

                       country country_code  region  gdp_per_capita_usd
103  Korea, Dem. People's Rep.          PRK     NaN                 NaN
104                Korea, Rep.          KOR     NaN        35674.095996

In [22]:
gdp_mapping = {
    'Korea, Rep.': 'South Korea'
}

gdp['country'] = gdp['country'].replace(gdp_mapping)

In [23]:
df = df.drop(columns=['gdp_per_capita_usd'])

df = df.merge(gdp[['country', 'gdp_per_capita_usd']], on='country', how='left')

In [24]:
df = df.drop(columns=['country_code', 'region'])
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population,gdp_per_capita_usd
0,1,Norway,18,12,11,41,Norway,5640194,87497.217965
1,2,United States of America,12,12,9,33,United States,345410175,81032.262118
2,3,Netherlands,10,7,3,20,Netherlands,18290019,63515.603078
3,4,Italy,10,6,14,30,Italy,58941446,39277.083878
4,5,Germany,8,10,8,26,Germany,83570702,54776.766824
5,6,France,8,9,6,23,France,67914198,44700.138418
6,7,Sweden,8,6,4,18,Sweden,10652755,54950.283473
7,8,Switzerland,6,9,8,23,Switzerland,9055930,100623.549627
8,9,Austria,5,8,5,18,Austria,9163189,56579.504175
9,10,Japan,5,7,12,24,Japan,122638865,33836.175627
10,11,Canada,5,7,9,21,Canada,40969904,54220.328504
11,12,People's Republic of China,5,4,6,15,China,1408902044,12951.178240
12,13,Republic of Korea,3,4,3,10,South Korea,51355773,35674.095996
13,14,Australia,3,2,1,6,Australia,27475920,65058.377315
14,15,Great Britain,3,1,1,5,United Kingdom,69709264,49944.470212
15,16,Czechia,2,2,1,5,Czechia,10712479,31761.594410
16,17,Slovenia,2,1,1,4,Slovenia,2124212,32660.475358
17,18,Spain,1,0,2,3,Spain,48710759,33493.222541
18,19,Brazil,1,0,0,1,Brazil,213491851,10377.589772
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20800815,12879.427526
20,21,Poland,0,3,1,4,Poland,37587594,22145.266065
21,22,New Zealand,0,2,1,3,New Zealand,5314739,49075.956283
22,23,Finland,0,1,5,6,Finland,5639673,52834.291675
23,24,Latvia,0,1,1,2,Latvia,1829717,22710.263754
24,25,Denmark,0,1,0,1,Denmark,6025989,68043.546697
25,25,Estonia,0,1,0,1,Estonia,1347008,30264.006489
26,25,Georgia,0,1,0,1,Georgia,3754571,8283.669607
27,28,Bulgaria,0,0,2,2,Bulgaria,6552509,15853.208637
28,29,Belgium,0,0,1,1,Belgium,11851553,55291.475454

## Merge Temperature data

In [25]:
temp.head()

       country  year  temperature
0  Afghanistan  1990        9.466
1  Afghanistan  1991        8.369
2  Afghanistan  1992        8.203
3  Afghanistan  1993        8.754
4  Afghanistan  1994        8.812

In [26]:
temp_5_years = temp[temp['year'].isin([2018,2019,2020,2021,2022])]
temp_5_years.head(10)

        country  year  temperature
28  Afghanistan  2018       10.910
29  Afghanistan  2019       10.010
30  Afghanistan  2020        9.569
31  Afghanistan  2021       11.180
32  Afghanistan  2022       10.820
61      Albania  2018       13.970
62      Albania  2019       13.790
63      Albania  2020       13.600
64      Albania  2021       13.390
65      Albania  2022       13.750

In [27]:
temp_new= temp_5_years.groupby('country', as_index=False)['temperature'].mean()

In [28]:
temp_new

         country  temperature
0    Afghanistan      10.4978
1        Albania      13.7000
2        Algeria      19.1940
3        Andorra       5.9584
4         Angola      23.0760
..           ...          ...
190    Venezuela      25.2160
191      Vietnam      25.1360
192        Yemen      24.0960
193       Zambia      22.3360
194     Zimbabwe      21.3300

[195 rows x 2 columns]

In [29]:
df = df.merge(temp_new, on='country', how='left')

In [30]:
df[df['temperature'].isna()]

,Rank,Country,Gold,Silver,Bronze,Total,country,population,gdp_per_capita_usd,temperature
1,2,United States of America,12,12,9,33,United States,345410175,81032.262118,NaN
12,13,Republic of Korea,3,4,3,10,South Korea,51355773,35674.095996,NaN

In [31]:
temp_new[temp_new['country'].str.contains("korea", case=False)]

        country  temperature
94  Korea, Rep.       13.352

In [32]:
temp_new[temp_new['country'].str.contains("united", case=False)]

                      country  temperature
183      United Arab Emirates      28.8160
184            United Kingdom      10.2528
185  United States of America      12.2240

In [33]:
temp_mapping = {
    'Korea, Rep.': 'South Korea',
    'United States of America' : 'United States'
}

temp_new['country'] = temp_new['country'].replace(temp_mapping)

In [34]:
df = df.drop(columns=['temperature'])

df = df.merge(temp_new[['country', 'temperature']], on='country', how='left')

In [35]:
df

,Rank,Country,Gold,Silver,Bronze,Total,country,population,gdp_per_capita_usd,temperature
0,1,Norway,18,12,11,41,Norway,5640194,87497.217965,4.1832
1,2,United States of America,12,12,9,33,United States,345410175,81032.262118,12.2240
2,3,Netherlands,10,7,3,20,Netherlands,18290019,63515.603078,11.1760
3,4,Italy,10,6,14,30,Italy,58941446,39277.083878,13.1340
4,5,Germany,8,10,8,26,Germany,83570702,54776.766824,10.4072
5,6,France,8,9,6,23,France,67914198,44700.138418,13.7100
6,7,Sweden,8,6,4,18,Sweden,10652755,54950.283473,6.3934
7,8,Switzerland,6,9,8,23,Switzerland,9055930,100623.549627,7.3770
8,9,Austria,5,8,5,18,Austria,9163189,56579.504175,8.0310
9,10,Japan,5,7,12,24,Japan,122638865,33836.175627,13.7060
10,11,Canada,5,7,9,21,Canada,40969904,54220.328504,0.5432
11,12,People's Republic of China,5,4,6,15,China,1408902044,12951.178240,13.2360
12,13,Republic of Korea,3,4,3,10,South Korea,51355773,35674.095996,13.3520
13,14,Australia,3,2,1,6,Australia,27475920,65058.377315,19.3880
14,15,Great Britain,3,1,1,5,United Kingdom,69709264,49944.470212,10.2528
15,16,Czechia,2,2,1,5,Czechia,10712479,31761.594410,9.5184
16,17,Slovenia,2,1,1,4,Slovenia,2124212,32660.475358,11.0480
17,18,Spain,1,0,2,3,Spain,48710759,33493.222541,14.8300
18,19,Brazil,1,0,0,1,Brazil,213491851,10377.589772,24.6060
19,19,Kazakhstan,1,0,0,1,Kazakhstan,20800815,12879.427526,7.1556
20,21,Poland,0,3,1,4,Poland,37587594,22145.266065,9.7012
21,22,New Zealand,0,2,1,3,New Zealand,5314739,49075.956283,12.0800
22,23,Finland,0,1,5,6,Finland,5639673,52834.291675,5.6714
23,24,Latvia,0,1,1,2,Latvia,1829717,22710.263754,7.7102
24,25,Denmark,0,1,0,1,Denmark,6025989,68043.546697,9.6826
25,25,Estonia,0,1,0,1,Estonia,1347008,30264.006489,7.1536
26,25,Georgia,0,1,0,1,Georgia,3754571,8283.669607,9.4212
27,28,Bulgaria,0,0,2,2,Bulgaria,6552509,15853.208637,12.1980
28,29,Belgium,0,0,1,1,Belgium,11851553,55291.475454,11.1260

## save dataset

In [37]:
df.to_csv("../data/processed/merged_data.csv")

## Add sports data

In [38]:
sports = pd.read_csv('../data/raw/medals_country_sports.csv')

In [40]:
df_sports = df.merge(sports, on="Country", how='left')

In [42]:
df_sports = df_sports.drop(columns=['Rank_y'])

In [44]:
df_sports.to_csv('../data/processed/merged_sports_data.csv')